In [1]:
import numpy as np
np.__version__

'1.24.3'

# Khoi tao array co ban

In [14]:
# Khai bao mang
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]], dtype=np.int64)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [10]:
# arr vs. print(arr) khac nhau?
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [13]:
# Thuoc tinh cua mang
print(f"Kieu du lieu: {arr.dtype}")
print(f"So phan tu: {arr.size}")
print(f"So chieu: {arr.ndim}")
print(f"Kich thuoc cac chieu: {arr.shape}")

Kieu du lieu: int64
So phan tu: 10
So chieu: 2
Kich thuoc cac chieu: (2, 5)


---

# Mot so cach khoi tao mang ndarray

## np.zeros(...)

In [15]:

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((3,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

## np.ones(...)

In [17]:
np.ones(4)

array([1., 1., 1., 1.])

In [19]:
np.ones([5,5], dtype=np.float64)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## np.full(...)

In [20]:
np.full((2,5), 99.97)

array([[99.97, 99.97, 99.97, 99.97, 99.97],
       [99.97, 99.97, 99.97, 99.97, 99.97]])

## np.arange([start,] stop[, step,])

In [21]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

## np.linspace(start, stop, [num=50])

In [25]:
# So phan tu mac dinh la 50
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [31]:
np.linspace(1,10,10, dtype=int)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## np.random

In [32]:
np.random.random(10)

array([0.26332914, 0.54496711, 0.40294746, 0.31243848, 0.88396847,
       0.73412971, 0.36903791, 0.04340055, 0.99637292, 0.13436178])

In [34]:
np.random.random((3,3))

array([[0.12420682, 0.47567022, 0.15021906],
       [0.26773655, 0.25987292, 0.55503319],
       [0.28201941, 0.11058707, 0.97698651]])

In [33]:
np.random.randint(1,100, 10)

array([55, 18, 52, 60, 93, 66, 75, 73, 54, 58])

In [35]:
np.random.randint(1,100, (5,5))

array([[ 5, 19, 79, 65, 45],
       [91, 68, 25, 76, 87],
       [97, 86, 97, 59, 33],
       [42, 21, 61, 76, 57],
       [23, 92, 99, 49, 30]])

## np.eye(...)

In [36]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])