In [1]:
import numpy as np
np.__version__

'1.24.3'

# Khoi tao array co ban

In [4]:
np.array(([1,2,3],[4,5,6]))

array([[1, 2, 3],
       [4, 5, 6]])

int vs np.int64

In [8]:
# Khai bao mang
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]], dtype=int)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [11]:
# Khai bao mang
arr = np.array([[1.5,2,3,4,5], [6,7,8,9,10]])
arr

array([[ 1.5,  2. ,  3. ,  4. ,  5. ],
       [ 6. ,  7. ,  8. ,  9. , 10. ]])

In [10]:
# arr vs. print(arr) khac nhau?
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [12]:
# Thuoc tinh cua mang
print(f"Kieu du lieu: {arr.dtype}")
print(f"So phan tu: {arr.size}")
print(f"So chieu: {arr.ndim}")
print(f"Kich thuoc cac chieu: {arr.shape}")

Kieu du lieu: float64
So phan tu: 10
So chieu: 2
Kich thuoc cac chieu: (2, 5)


---

# Mot so cach khoi tao mang ndarray

## np.zeros(...)

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((3,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [15]:
np.zeros((3,4,5), dtype=int)

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

## np.ones(...)

In [16]:
np.ones(4)

array([1., 1., 1., 1.])

In [19]:
np.ones([5,5], dtype=np.float64)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## np.full(...)

In [20]:
np.full((2,5), 1000)

array([[1000, 1000, 1000, 1000, 1000],
       [1000, 1000, 1000, 1000, 1000]])

## np.arange([start,] stop[, step,])

In [22]:
#similar

for i in range(1,10,2):
    print(i)


range(1,10,2)

1
3
5
7
9


range(1, 10, 2)

In [21]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

## np.linspace(start, stop, [num=50])

In [25]:
# So phan tu mac dinh la 50
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [31]:
np.linspace(1,10,10, dtype=int)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## np.random

In [30]:
# Normal distribution
np.random.random(10)

array([0.4245082 , 0.41916794, 0.56232228, 0.66308781, 0.64372689,
       0.32288998, 0.50397924, 0.97377513, 0.0428163 , 0.06265194])

In [34]:
np.random.random((3,3))

array([[0.12420682, 0.47567022, 0.15021906],
       [0.26773655, 0.25987292, 0.55503319],
       [0.28201941, 0.11058707, 0.97698651]])

In [33]:
# Start, Stop, shape of elements
np.random.randint(1,100, 10)

array([55, 18, 52, 60, 93, 66, 75, 73, 54, 58])

In [35]:
np.random.randint(1,100, (5,5))

array([[52, 24, 42,  2, 60],
       [41, 10, 15, 76, 21],
       [83, 69, 36, 31, 33],
       [87,  3, 80, 25, 23],
       [39, 46, 21, 46, 67]])

"Random" -> Pseudorandom

## np.eye(...)

In [36]:
# eye -> Identity
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])