In [1]:
import numpy as np

# Ex1

Tạo mảng có kích thước $3\times3$ bao gồm các số nguyên ngẫu nhiên từ 1 $\longrightarrow$ 100

Reshape thành mảng 1 chiều

In [2]:
a = np.random.randint(1,100, (3,3))
a

array([[80, 53, 76],
       [10, 91, 52],
       [22, 13, 48]])

In [3]:
a.reshape(-1)

array([80, 53, 76, 10, 91, 52, 22, 13, 48])

Truy cập 2 hàng đầu, 2 cột đầu của mảng trên

In [4]:
a_con = a[:2,:2]
a_con

array([[80, 53],
       [10, 91]])

Lấy các thuộc tính cơ bản của mảng

In [5]:
a.shape

(3, 3)

In [6]:
a.dtype

dtype('int64')

In [7]:
a.nbytes

72

In [8]:
a.ndim

2

Lưu ý

In [11]:
b = a.reshape(-1,)
b

array([80, 53, 76, 10, 91, 52, 22, 13, 48])

In [16]:
b.shape

(9,)

# Ex2

Nối mảng

- np.concatenate
- np.vstack
- np.hstack

Tạo 2 mảng có kích thước $3\times3$ bao gồm các số nguyên ngẫu nhiên từ 1 $\longrightarrow$ 100

In [18]:
a = np.random.randint(1,100, (3,3))
b = np.random.randint(1,100, (3,3))

a,b

(array([[74, 15, 89],
        [44, 32, 18],
        [60, 11, 61]]),
 array([[12, 48, 36],
        [43, 82, 84],
        [11, 22,  9]]))

In [22]:
a.shape

(3, 3)

Ghép thành mảng $6\times3$

In [20]:
c = np.concatenate([a,b])
c = np.concatenate([a,b], axis=0)
c, c.shape

(array([[74, 15, 89],
        [44, 32, 18],
        [60, 11, 61],
        [12, 48, 36],
        [43, 82, 84],
        [11, 22,  9]]),
 (6, 3))

In [21]:
np.vstack([a,b])

array([[74, 15, 89],
       [44, 32, 18],
       [60, 11, 61],
       [12, 48, 36],
       [43, 82, 84],
       [11, 22,  9]])

Ghép thành mảng $3\times6$

In [23]:
d = np.concatenate([a,b], axis=1)

d, d.shape

(array([[74, 15, 89, 12, 48, 36],
        [44, 32, 18, 43, 82, 84],
        [60, 11, 61, 11, 22,  9]]),
 (3, 6))

In [24]:
np.hstack([a,b])

array([[74, 15, 89, 12, 48, 36],
       [44, 32, 18, 43, 82, 84],
       [60, 11, 61, 11, 22,  9]])

# Ex3

tạo 1 array 1 chiều gồm 26 phần tử

In [26]:
a = np.arange(26)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])

Tách array thành 4 array con, sao cho các array con đều nhau nhất có thể (về số lượng)

- coi 26 là hằng số (tính toán với nó được)
- KHông chơi hardcode (split theo index định nghĩa sẵn)

- 7,7,7,5
- 7,7,6,6

# Extra

Cho ma trận kích thước $2000\times1000$

In [29]:
a = np.random.randint(1,10000, (2000,1000))
a

array([[6490, 6307, 3298, ..., 5069, 2204, 6402],
       [5949, 2664, 4279, ..., 9211, 2882, 2798],
       [5038, 7254, 5257, ..., 8188, 3638,  518],
       ...,
       [5408, 1999, 3799, ..., 9058,  734, 2041],
       [1701, 9192, 6519, ..., 5815, 3119, 8432],
       [7022, 6601, 7419, ..., 6932, 2656, 5773]])

Cho vector có chiều dài 1000, giá trị của từng element 1 -> 1000

In [32]:
b = np.random.randint(0,999,1000)

Yêu cầu: Với mỗi hàng ở trong A, lấy ra cột được xác định trong B

Ví dụ:
- b[0] = 440

    Thì hàng 0 của a -> lấy giá trị của cột thứ 440

- b[1] = 750

    Thì hàng 1 của a -> lấy giá trị của cột thứ 750

Kết qủa là 1 vector cùng chiều với B